### ISSUE TITLE
Mongodb connection error

### ISSUE THREAD

**Issue by kingcodak** [moonfo-youtube-tutorials/frontend-side-mern-blog-app#1]
I am having issues connecting the mongodb. the app is working fine, but once i import the mongoose db the server.js. it will show this error in the terminal.
![code error](https://github.com/mohammadrz003/moonfo-youtube/assets/135263132/fe3cfd03-b312-46e2-a8f3-b4849f191ef9)

**Comment by mohammadrz003** [comment]
what's your `mongoose` version?
I think you installed the latest version which is version 7 at this moment...
try to downgrade that to version 6.9.2 which I'm using in the YouTube tutorial.
just run the command below in the root of your backend project and then you're good to go:
npm install mongoose@6.9.2

**Comment by mohammadrz003** [comment]
> I am having issues connecting the mongodb. the app is working fine, but once i import the mongoose db the server.js. it will show this error in the terminal. ![code error](https://user-images.githubusercontent.com/135263132/284336010-fe3cfd03-b312-46e2-a8f3-b4849f191ef9.PNG)

what's your mongoose version?
I think you installed the latest version which is version 7 at this moment...
try to downgrade that to version 6.9.2 which I'm using in the YouTube tutorial.
just run the command below in the root of your backend project and then you're good to go:
`npm install mongoose@6.9.2`

**Comment by kingcodak** [comment]
Okay, I have downgraded it and it is working fine now. But i will suggest you find a way to solve it so it will work with the latest version of mongoose. maybe try using prisma.

**Comment by mohammadrz003** [comment]
> Okay, I have downgraded it and it is working fine now. But i will suggest you find a way to solve it so it will work with the latest version of mongoose. maybe try using prisma.

you know, it is ok and natural that each version of a library has some breaking changes and it's on you whether you want to keep your code updated with the latest changes or not.
it doesn't matter whether I use mongoose or prisma because all the libraries may make some breaking changes when they release a new version.

**Comment by kingcodak** [comment]
Okay, i understand. thanks for the project. Am learning from it.

**Comment by kingcodak** [comment]
Hello, i noticed the text editor is not working fine, when you click on add new post, it will automatically, publish the sample data, without clicking on publish and what shows is update post, when you have not publish any post before

**Comment by mohammadrz003** [comment]
> Hello, i noticed the text editor is not working fine, when you click on add new post, it will automatically, publish the sample data, without clicking on publish and what shows is update post, when you have not publish any post before

I consciously made the project like this, but you're right, it needs improvement.
I've made a separate issue on this.
